/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\robot.glb 
Author: Sadzony (https://sketchfab.com/Sadzony)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-2d96f787eb514519a31df518648777bb
Title: Robot
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Robot(props) {
  const { nodes, materials } = useGLTF('./robot.glb')
  const cast = false
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh castShadow={cast} geometry={nodes.Object_2.geometry} material={materials.lambert5SG} />
        <mesh castShadow={cast} geometry={nodes.Object_3.geometry} material={materials.lambert5SG} />
        <mesh castShadow={cast} geometry={nodes.Object_4.geometry} material={materials.lambert5SG} />
        <mesh castShadow={cast} geometry={nodes.Object_5.geometry} material={materials.lambert5SG} />
        <mesh castShadow={cast} geometry={nodes.Object_6.geometry} material={materials.lambert5SG} />
        <mesh castShadow={cast} geometry={nodes.Object_7.geometry} material={materials.lambert5SG} />
      </group>
    </group>
  )
}

useGLTF.preload('./robot.glb')
